server:
  port: 8083
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mohirdev
    username: mohirdev
    password: 1234
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
      ddl-auto: update
